
// This file is automatically generated. Do not edit it directly.
import { supabase } from "@/lib/supabase";

// Import the supabase client from src/lib/supabase.ts like this:
// import { supabase } from "@/lib/supabase";

export { supabase };
